# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Windows (Framework Dependent)
      run: dotnet publish -r win-x64 -c Release -f net8.0 --self-contained false -o ./publish-win /p:PublishSingleFile=true /p:PublishTrimmed=false /p:TrimMode=full /p:PublishAot=false /p:InvariantGlobalization=true
    - name: Publish Linux (Framework Dependent)
      run: dotnet publish -r linux-x64 -c Release -f net8.0 --self-contained false -o ./publish /p:PublishSingleFile=true /p:PublishTrimmed=false /p:TrimMode=full /p:PublishAot=false /p:InvariantGlobalization=true
    - name: Publish Linux (Native AOT)
      run: dotnet publish -r linux-x64 -c Release -f net8.0 --self-contained false -o ./publish-aot /p:PublishSingleFile=false /p:PublishTrimmed=true /p:TrimMode=full /p:PublishAot=true /p:InvariantGlobalization=true /p:Version=2.1.0
    
    # Upload published files as artifacts
    - name: Upload Windows publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish-win
        path: ./publish-win

    - name: Upload Linux publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish-linux
        path: ./publish

    - name: Upload Linux Native AOT publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish-native
        path: ./publish-native
